# Set the C compiler and flags.
CC = gcc
CFLAGS = -O2 #-fopenmp

# Set flags for spring2.0.
AR = ar
ARFLAGS = cr
RANLIB = ranlib

LIB = -Lsprng2.0/lib -lm -lsprng # -lm required for -DVERIFYK4
INC = -Isprng2.0/include

# Set CUDA compiler and flags.
NVCC = nvcc
NVCCFLAGS =
GENCODE_FLAGS =

# Set linker and flags.
LD = nvcc
LDFLAGS =
