#!/bin/bash

# Check if it is running the main4-core CPU cluster ("G")
# or the 5th low-power shadow core ("LP").
cat /sys/kernel/cluster/active

# Check which of the 4 CPU cores are currently running (online).
cat /sys/devices/system/cpu/online

# Check current CPU clock frequencies.
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq
cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq
cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq
