#!/bin/bash


for scale in 1 2 3 4 5 6 7 8 9 10 11
do
  avg_time=0.0
  echo "SCALE $scale"
  for i in 0 1 2 3 4
  do
    ./../gpu/SSCA2 $scale 2>&1 | awk '/^Time taken for Kernel 4/ { print $7 }'
  done
done
